import HackathonCard from "@/components/HackathonCard";
import Container from "@mui/joy/Container";
import Head from "next/head";
import Grid from "@mui/joy/Grid";
import Typography from "@mui/joy/Typography";
import Box from "@mui/joy/Box";
import Image from "next/image";
import List from "@mui/joy/List";
import ListDivider from "@mui/joy/ListDivider";
import Button from "@mui/joy/Button";
import Avatar from "@mui/joy/Avatar";
import * as Accordion from "@radix-ui/react-accordion";

import { AccordionHeader, AccordionContent } from "@/components/JoyAccordion";
import GeneralLayout from "@/layouts/GeneralLayout";

export default function Home() {
  return (
    <GeneralLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component={"main"}>
        <Container
          sx={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
            maxHeight: "748px",
          }}
        >
          <Typography
            level="h1"
            fontSize={["3rem", "4.5rem", "5.5rem", "6.5rem"]}
            textAlign={"center"}
            mb={0}
            sx={{
              textWrap: "balance",
            }}
          >
            Join a virtual{" "}
            <Box
              component={"span"}
              sx={{
                display: "inline-block",
                wordBreak: "pre-line",
              }}
            >
              tech
              <span
                style={{
                  display: "inline-block",
                  color: "transparent",
                  backgroundImage:
                    "linear-gradient(99.72deg, rgb(44, 105, 209) 7.35%, rgb(10, 188, 249) 86.94%);",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                }}
              >
                Fiesta
              </span>
            </Box>
          </Typography>
          <Typography
            level="body-lg"
            fontSize={"1.5rem"}
            textAlign={"center"}
            mb={6}
          >
            Particpate in hackathons where developers thrive, ideas flourish,
            and success begins.
          </Typography>
          <Button size="lg" sx={{ px: 6 }}>
            Get Started Now
          </Button>
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-around",
              width: "100%",
              mt: 12,
            }}
          >
            <Avatar
              src="https://www.techfiesta.dev/images/mask1.svg"
              sx={{
                width: 80,
                height: 80,
                top: -80,
              }}
            />
            <Avatar
              src="https://www.techfiesta.dev/images/mask2.svg"
              sx={{
                width: 80,
                height: 80,
                top: -40,
              }}
            />
            <Avatar
              src="https://www.techfiesta.dev/images/mask3.svg"
              sx={{
                width: 120,
                height: 120,
              }}
            />
            <Avatar
              src="https://www.techfiesta.dev/images/mask4.svg"
              sx={{
                width: 80,
                height: 80,
                top: -40,
              }}
            />
            <Avatar
              src="https://www.techfiesta.dev/images/mask5.svg"
              sx={{
                width: 80,
                height: 80,
                top: -80,
              }}
            />
          </Box>
        </Container>
      </Box>
      <Container>
        <Typography level="h1" mb={2} textAlign={"center"}>
          FEATURED HACKATHONS
        </Typography>
        <Grid
          container
          rowSpacing={1}
          columnSpacing={2}
          sx={{ width: "100%", my: 6, mr: 0, ml: 0 }}
        >
          <Grid xs={12} md={6}>
            <HackathonCard
              bounty={5000}
              host="Celo & Bunzz"
              participants={49}
              title="CELO X Bunzz Hackathon"
              displayImage="https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg"
            />
          </Grid>
          <Grid xs={12} md={6}>
            <HackathonCard
              bounty={200}
              host="HUMAN Protocol"
              participants={20}
              title="Building On The HUMAN Protocol"
              displayImage="https://linktr.ee/og/image/human_protocol.jpg"
            />
          </Grid>
        </Grid>

        <Box my={12}>
          <Typography level="h1" mb={2} textAlign={"center"}>
            Benefits of participating in techFiesta Hackathons
          </Typography>
          <Box
            sx={{
              display: ["block", "block", "flex"],
              flexDirection: "row",
              alignItems: "center",
              gap: 4,
              mt: 6,
            }}
          >
            <Box
              flex={1}
              height={300}
              display={"flex"}
              alignItems={"center"}
              justifyContent={"center"}
              py={22.5}
              borderRadius={6}
              sx={{
                backgroundImage:
                  "linear-gradient(rgb(11, 165, 236), rgb(29, 41, 57))",
              }}
            >
              <Image
                src="https://www.techfiesta.dev/images/grants.svg"
                alt="Hero"
                width={250}
                height={250}
              />
            </Box>
            <Box flex={1}>
              <Typography
                level="h2"
                sx={{
                  textWrap: "balance",
                }}
              >
                Grants and Support from Hackathon Sponsors
              </Typography>
              <Typography level="body-lg" my={3}>
                Receive grants and support from hackathon sponsors as you work
                on building groundbreaking projects. You can get financial
                backing and guidance from companies that recognize and value
                your entrepreneurial spirit.
              </Typography>
            </Box>
          </Box>
          <Box
            sx={{
              display: ["block", "block", "flex"],
              flexDirection: "row-reverse",
              alignItems: "center",
              gap: 4,
              mt: 10,
            }}
          >
            <Box
              flex={1}
              height={300}
              display={"flex"}
              alignItems={"center"}
              justifyContent={"center"}
              py={22.5}
              borderRadius={6}
              sx={{
                backgroundImage:
                  "linear-gradient(rgb(11, 165, 236), rgb(29, 41, 57))",
              }}
            >
              <Box
                width={400}
                height={400}
                display={"flex"}
                alignItems={"center"}
                justifyContent={"center"}
              >
                <Image
                  src="https://www.techfiesta.dev/images/skill.svg"
                  alt="Hero"
                  width={400}
                  height={400}
                  layout="responsive"
                />
              </Box>
            </Box>
            <Box flex={1}>
              <Typography
                level="h2"
                sx={{
                  textWrap: "balance",
                }}
              >
                Access to Upskilling Opportunities
              </Typography>
              <Typography level="body-lg" my={3}>
                As a member of techFiesta, you gain access to a wealth of
                upskilling opportunities, including educational workshops,
                seminars, and events, enabling you to stay ahead of the curve in
                the ever-evolving tech landscape.
              </Typography>
            </Box>
          </Box>
        </Box>

        <Box sx={{ pb: 12 }} maxWidth={"md"} mx={"auto"}>
          <Typography level="h1" my={6} textAlign={"center"}>
            F.A.Qs
          </Typography>
          <List
            variant="outlined"
            component={Accordion.Root}
            type="multiple"
            defaultValue={["item-1"]}
            sx={{
              borderRadius: "xs",
              "--ListDivider-gap": "0px",
              "--focus-outline-offset": "-2px",
            }}
          >
            <Accordion.Item value="item-1">
              <AccordionHeader isFirst>
                How do I participate in a techFiesta hackathon?
              </AccordionHeader>
              <AccordionContent>
                <Typography>
                  Participating in a techFiesta hackathon is easy! Simply browse
                  through the ongoing hackathons and select the one that
                  interests you and click on the &ldquo;Register&rdquo; button.
                  Create your profile, and you&apos;ll be ready to dive into the
                  exciting world of hackathons!
                </Typography>
              </AccordionContent>
            </Accordion.Item>

            <ListDivider component="div" />

            <Accordion.Item value="item-2">
              <AccordionHeader>
                How are payments made to developers after a hackathon?
              </AccordionHeader>
              <AccordionContent>
                At techFiesta, we ensure fast and secure payments through our
                partnership with HUMAN Protocol. Once your work has been
                evaluated and approved by the hackathon sponsor, payments are
                triggered and processed via stablecoins using HUMAN
                Protocol&apos;s escrow system. This eliminates any disputes or
                delays, ensuring a seamless payment experience.
              </AccordionContent>
            </Accordion.Item>

            <ListDivider component="div" />

            <Accordion.Item value="item-3">
              <AccordionHeader>
                Are there any educational resources available for developers on
                techFiesta?
              </AccordionHeader>
              <AccordionContent>
                Absolutely! As a techFiesta participant, you gain access to a
                wealth of educational resources. We offer educational workshops,
                seminars, and events where you can enhance your skills and stay
                updated with the latest technologies. We believe in continuous
                learning and provide opportunities for developers to upskill and
                grow.
              </AccordionContent>
            </Accordion.Item>

            <ListDivider component="div" />

            <Accordion.Item value="item-4">
              <AccordionHeader>
                Can I collaborate with other developers during a hackathon?
              </AccordionHeader>
              <AccordionContent>
                Collaboration is highly encouraged at techFiesta hackathons! Our
                platform provides real-time interaction and communication
                channels where you can connect with other developers, form
                teams, and collaborate on projects. This collaborative
                environment fosters innovation, allows for knowledge sharing,
                and creates a vibrant community of like-minded individuals.
              </AccordionContent>
            </Accordion.Item>

            <ListDivider component="div" />

            <Accordion.Item value="item-5">
              <AccordionHeader>
                Are the hackathons only for developers?
              </AccordionHeader>
              <AccordionContent>
                We welcome anyone with an interest in technology, innovation,
                and collaborative problem-solving. Whether you are a developer,
                project manager, designer, entrepreneur, or tech enthusiast, you
                can participate in our hackathons and benefit from the
                opportunities and resources we offer.
              </AccordionContent>
            </Accordion.Item>

            <ListDivider component="div" />

            <Accordion.Item value="item-6">
              <AccordionHeader isLast>
                Why do I need techFiesta?
              </AccordionHeader>
              <AccordionContent isLast>
                techFiesta offers a unique platform to showcase your skills,
                connect with top companies, and gain recognition in the tech
                industry. By participating in our hackathons, you can accelerate
                your learning, expand your network, and have the chance to birth
                innovative solutions. Additionally, you receive bounties on
                chain in stable coins and we provide access to educational
                workshops and upskilling opportunities. Joining techFiesta opens
                doors to valuable experiences, collaborations, and career growth
                in the tech ecosystem.
              </AccordionContent>
            </Accordion.Item>
          </List>
        </Box>
      </Container>
    </GeneralLayout>
  );
}
